/*
 * Copyright (c) 2026 Jyotishko Roy. All rights reserved. No permission is granted to copy, modify, distribute, sublicense, host, sell,
 * commercially use, train models on, scrape, or create derivative works from this
 * repository or any part of it without prior written permission from Jyotishko Roy.
 */

import type { ReportFieldRiskLevel, ReportFieldSourceType } from './field-source-types.ts';
import type { UnavailableReason } from './unavailable.ts';

export type AstroReportFieldRegistryEntry = {
  groupId: string;
  groupName: string;
  fieldKey: string;
  displayLabel: string;
  sourceType: ReportFieldSourceType;
  requiredChartPaths: string[];
  calculationModule?: string;
  dbTable?: string;
  dbJsonPath?: string;
  route?: string;
  testIds: string[];
  unavailablePolicy: {
    reason: UnavailableReason;
    requiredModule?: string;
  };
  riskLevel: ReportFieldRiskLevel;
  versionedSettingsRequired: string[];
  enabled: boolean;
};

export const ASTRO_REPORT_FIELD_REGISTRY: readonly AstroReportFieldRegistryEntry[] = [
  { groupId: 'profile_input', groupName: 'Profile Input', fieldKey: 'display_name', displayLabel: 'Display Name', sourceType: 'input_display', requiredChartPaths: ['metadata.profile_id'], testIds: ['report-field-display-name'], unavailablePolicy: { reason: 'field_not_registered' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'profile_input', groupName: 'Profile Input', fieldKey: 'birth_date', displayLabel: 'Birth Date', sourceType: 'input_display', requiredChartPaths: ['metadata.birth_date', 'birth_data.birth_date'], testIds: ['report-field-birth-date'], unavailablePolicy: { reason: 'field_not_registered' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'profile_input', groupName: 'Profile Input', fieldKey: 'birth_time', displayLabel: 'Birth Time', sourceType: 'input_display', requiredChartPaths: ['birth_data.birth_time', 'metadata.birth_time'], testIds: ['report-field-birth-time'], unavailablePolicy: { reason: 'field_not_registered' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'profile_input', groupName: 'Profile Input', fieldKey: 'birth_place', displayLabel: 'Birth Place', sourceType: 'input_display', requiredChartPaths: ['birth_data.birth_place_name', 'metadata.birth_place_name'], testIds: ['report-field-birth-place'], unavailablePolicy: { reason: 'field_not_registered' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'core_chart', groupName: 'Core Chart', fieldKey: 'lagna_sign', displayLabel: 'Lagna Sign', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.lagna.fields.ascendant.sign', 'canonical_chart_json_v2.sections.lagna.fields.sign', 'sections.lagna.fields.ascendant.sign', 'sections.lagna.fields.sign', 'lagna.sign', 'd1.lagna.sign', 'ascendant.sign'], calculationModule: 'lagna', testIds: ['report-field-lagna-sign'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'lagna' }, riskLevel: 'MEDIUM', versionedSettingsRequired: ['zodiac_type', 'ayanamsa', 'house_system'], enabled: true },
  { groupId: 'core_chart', groupName: 'Core Chart', fieldKey: 'moon_sign', displayLabel: 'Moon Sign', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Moon.sign', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Moon.sign', 'sections.planetaryPositions.fields.byBody.Moon.sign', 'planetary_positions.Moon.sign', 'planets.Moon.sign', 'moon.sign'], calculationModule: 'planetary_positions', testIds: ['report-field-moon-sign'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'planetary_positions' }, riskLevel: 'MEDIUM', versionedSettingsRequired: ['zodiac_type', 'ayanamsa'], enabled: true },
  { groupId: 'core_chart', groupName: 'Core Chart', fieldKey: 'sun_sign', displayLabel: 'Sun Sign', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Sun.sign', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Sun.sign', 'sections.planetaryPositions.fields.byBody.Sun.sign', 'planetary_positions.Sun.sign', 'planets.Sun.sign', 'sun.sign'], calculationModule: 'planetary_positions', testIds: ['report-field-sun-sign'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'planetary_positions' }, riskLevel: 'MEDIUM', versionedSettingsRequired: ['zodiac_type', 'ayanamsa'], enabled: true },
  { groupId: 'core_chart', groupName: 'Core Chart', fieldKey: 'moon_house', displayLabel: 'Moon House', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Moon.house', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Moon.house', 'canonical_chart_json_v2.sections.houses.fields.moon_house', 'houses.moon_house', 'planets.Moon.house', 'moon.house'], calculationModule: 'houses', testIds: ['report-field-moon-house'], unavailablePolicy: { reason: 'incompatible_settings', requiredModule: 'houses' }, riskLevel: 'HIGH', versionedSettingsRequired: ['house_system'], enabled: true },
  { groupId: 'core_chart', groupName: 'Core Chart', fieldKey: 'sun_house', displayLabel: 'Sun House', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Sun.house', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Sun.house', 'canonical_chart_json_v2.sections.houses.fields.sun_house', 'houses.sun_house', 'planets.Sun.house', 'sun.house'], calculationModule: 'houses', testIds: ['report-field-sun-house'], unavailablePolicy: { reason: 'incompatible_settings', requiredModule: 'houses' }, riskLevel: 'HIGH', versionedSettingsRequired: ['house_system'], enabled: true },
  { groupId: 'dosha', groupName: 'Dosha', fieldKey: 'manglik', displayLabel: 'Manglik Dosha', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.dosha.fields.manglik', 'dosha.manglik'], calculationModule: 'dosha', testIds: ['report-field-manglik-dosha'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'dosha' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'dosha', groupName: 'Dosha', fieldKey: 'kalsarpa', displayLabel: 'Kalsarpa Boundary', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.dosha.fields.kalsarpa', 'dosha.kalsarpa'], calculationModule: 'dosha', testIds: ['report-field-kalsarpa'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'dosha' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'dosha', groupName: 'Dosha', fieldKey: 'safe_remedies', displayLabel: 'Safe Remedies', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.dosha.fields.safeRemedies', 'dosha.safeRemedies'], calculationModule: 'dosha', testIds: ['report-field-safe-remedies'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'dosha' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'yoga', groupName: 'Yoga', fieldKey: 'gajakesari', displayLabel: 'Gajakesari Yoga', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.yoga.fields.rules.gajakesari', 'yoga.rules.gajakesari'], calculationModule: 'yoga', testIds: ['report-field-gajakesari'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'yoga' }, riskLevel: 'MEDIUM', versionedSettingsRequired: [], enabled: true },
  { groupId: 'yoga', groupName: 'Yoga', fieldKey: 'chandra_mangal', displayLabel: 'Chandra-Mangal Yoga', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.yoga.fields.rules.chandraMangal', 'yoga.rules.chandraMangal'], calculationModule: 'yoga', testIds: ['report-field-chandra-mangal'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'yoga' }, riskLevel: 'MEDIUM', versionedSettingsRequired: [], enabled: true },
  { groupId: 'yoga', groupName: 'Yoga', fieldKey: 'budha_aditya', displayLabel: 'Budha-Aditya Yoga', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.yoga.fields.rules.budhaAditya', 'yoga.rules.budhaAditya'], calculationModule: 'yoga', testIds: ['report-field-budha-aditya'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'yoga' }, riskLevel: 'MEDIUM', versionedSettingsRequired: [], enabled: true },
  { groupId: 'nakshatra', groupName: 'Nakshatra', fieldKey: 'moon_nakshatra', displayLabel: 'Moon Nakshatra', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Moon.nakshatra', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Moon.nakshatra', 'moon.nakshatra', 'planets.Moon.nakshatra'], calculationModule: 'nakshatra', testIds: ['report-field-moon-nakshatra'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'nakshatra' }, riskLevel: 'HIGH', versionedSettingsRequired: ['zodiac_type', 'ayanamsa'], enabled: true },
  { groupId: 'nakshatra', groupName: 'Nakshatra', fieldKey: 'moon_nakshatra_pada', displayLabel: 'Moon Nakshatra Pada', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.planetaryPositions.fields.byBody.Moon.nakshatra_pada', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Moon.nakshatra_pada', 'moon.nakshatra_pada', 'planets.Moon.nakshatra_pada'], calculationModule: 'nakshatra', testIds: ['report-field-moon-nakshatra-pada'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'nakshatra' }, riskLevel: 'HIGH', versionedSettingsRequired: ['zodiac_type', 'ayanamsa'], enabled: true },
  { groupId: 'dasha', groupName: 'Dasha', fieldKey: 'current_mahadasha', displayLabel: 'Current Mahadasha', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.vimshottari.fields.currentMahadasha.lord', 'canonical_chart_json_v2.sections.vimshottari.fields.current_mahadasha', 'vimshottari_dasha.current_mahadasha', 'vimshottari.currentMahadasha', 'dasha.current.mahadasha'], calculationModule: 'vimshottari', testIds: ['report-field-current-mahadasha'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'vimshottari' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'dasha', groupName: 'Dasha', fieldKey: 'current_antardasha', displayLabel: 'Current Antardasha', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.vimshottari.fields.currentAntardasha.lord', 'canonical_chart_json_v2.sections.vimshottari.fields.current_antardasha', 'vimshottari_dasha.current_antardasha', 'vimshottari.currentAntardasha', 'dasha.current.antardasha'], calculationModule: 'vimshottari', testIds: ['report-field-current-antardasha'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'vimshottari' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'dasha', groupName: 'Dasha', fieldKey: 'dasha_timeline', displayLabel: 'Dasha Timeline', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.vimshottari.fields.timeline', 'vimshottari_dasha.timeline', 'vimshottari.timeline', 'dasha.timeline'], calculationModule: 'vimshottari', testIds: ['report-field-dasha-timeline'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'vimshottari' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'kp', groupName: 'KP', fieldKey: 'kp_ayanamsha', displayLabel: 'KP Ayanamsha', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.kp.fields.kpAyanamshaDeg', 'canonical_chart_json_v2.sections.kp.fields.byBody', 'kp.kpAyanamshaDeg'], calculationModule: 'kp', testIds: ['report-field-kp-ayanamsha'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'kp' }, riskLevel: 'HIGH', versionedSettingsRequired: ['ayanamsa'], enabled: true },
  { groupId: 'kp', groupName: 'KP', fieldKey: 'kp_significators', displayLabel: 'KP Significators', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.kp.fields.significators', 'kp.significators'], calculationModule: 'kp_significators', testIds: ['report-field-kp-significators'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'kp_significators' }, riskLevel: 'BLOCKER', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'shadbala', displayLabel: 'Shadbala', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.shadbala', 'shadbala'], calculationModule: 'shadbala', testIds: ['report-field-shadbala'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'shadbala' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'ashtakavarga', displayLabel: 'Ashtakavarga', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.ashtakavarga', 'ashtakavarga'], calculationModule: 'ashtakavarga', testIds: ['report-field-ashtakavarga'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'ashtakavarga' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'ashtakavarga_total', displayLabel: 'Ashtakavarga Total', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.ashtakavarga.fields.sarvashtakavargaTotal.grandTotal', 'canonical_chart_json_v2.sections.ashtakavarga.fields.sarvashtakavargaTotal.totalsBySign', 'canonical_chart_json_v2.sections.ashtakavarga.fields.sarvashtakavargaTotal'], calculationModule: 'ashtakavarga', testIds: ['report-field-ashtakavarga-total'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'ashtakavarga_total' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'ashtakavarga_bindu_matrix', displayLabel: 'Ashtakavarga Bindu Matrix', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.ashtakavarga.fields.binduMatrix', 'ashtakavarga.binduMatrix'], calculationModule: 'ashtakavarga_bindu_matrix', testIds: ['report-field-ashtakavarga-bindu-matrix'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'ashtakavarga_bindu_matrix' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'transit_prediction_timing', displayLabel: 'Transit Prediction Timing', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.transits.fields.predictionTiming', 'transits.predictionTiming'], calculationModule: 'transit_prediction_timing', testIds: ['report-field-transit-prediction-timing'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'transit_prediction_timing' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'varshaphal', displayLabel: 'Varshaphal', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.varshaphal', 'varshaphal'], calculationModule: 'varshaphal', testIds: ['report-field-varshaphal'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'varshaphal' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'yogini_dasha', displayLabel: 'Yogini Dasha', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.yoginiDasha', 'yogini_dasha'], calculationModule: 'yogini_dasha', testIds: ['report-field-yogini-dasha'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'yogini_dasha' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'chara_dasha', displayLabel: 'Chara Dasha', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.charaDasha', 'chara_dasha'], calculationModule: 'chara_dasha', testIds: ['report-field-chara-dasha'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'chara_dasha' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'lal_kitab_judgement', displayLabel: 'Lal Kitab Judgement', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.lalKitabJudgement', 'lal_kitab_judgement'], calculationModule: 'lal_kitab_judgement', testIds: ['report-field-lal-kitab-judgement'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'lal_kitab_judgement' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'sade_sati_dates', displayLabel: 'Sade Sati Dates', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.sadeSatiDates', 'sade_sati_dates'], calculationModule: 'sade_sati_dates', testIds: ['report-field-sade-sati-dates'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'sade_sati_dates' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'panchang_convention', displayLabel: 'Panchang Convention', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.convention', 'panchang.convention', 'metadata.calculation_settings.panchang_convention'], calculationModule: 'panchang', testIds: ['report-field-panchang-convention'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'panchang' }, riskLevel: 'MEDIUM', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'tithi', displayLabel: 'Tithi', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.tithi', 'sections.panchang.fields.tithi', 'panchang.fields.tithi', 'panchang.tithi'], calculationModule: 'panchang', testIds: ['report-field-tithi'], unavailablePolicy: { reason: 'missing_golden_fixture', requiredModule: 'panchang' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'paksha', displayLabel: 'Paksha', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.paksha', 'sections.panchang.fields.paksha', 'panchang.fields.paksha', 'panchang.paksha'], calculationModule: 'panchang', testIds: ['report-field-paksha'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'panchang' }, riskLevel: 'MEDIUM', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'yoga', displayLabel: 'Yoga', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.yoga', 'sections.panchang.fields.yoga', 'panchang.fields.yoga', 'panchang.yoga'], calculationModule: 'panchang', testIds: ['report-field-yoga'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'panchang' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'karana', displayLabel: 'Karana', sourceType: 'astronomical_calculation', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.karana', 'sections.panchang.fields.karana', 'panchang.fields.karana', 'panchang.karana'], calculationModule: 'panchang', testIds: ['report-field-karana'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'panchang' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'panchang', groupName: 'Panchang', fieldKey: 'weekday', displayLabel: 'Weekday', sourceType: 'deterministic_derived', requiredChartPaths: ['canonical_chart_json_v2.sections.panchang.fields.weekday', 'sections.panchang.fields.weekday', 'panchang.fields.weekday', 'panchang.weekday', 'panchang.vara'], calculationModule: 'panchang', testIds: ['report-field-weekday'], unavailablePolicy: { reason: 'missing_chart_path', requiredModule: 'panchang' }, riskLevel: 'SAFE', versionedSettingsRequired: [], enabled: true },
  { groupId: 'advanced', groupName: 'Advanced', fieldKey: 'outer_planets', displayLabel: 'Outer Planets', sourceType: 'unavailable', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.outerPlanets'], calculationModule: 'advanced', testIds: ['report-field-outer-planets'], unavailablePolicy: { reason: 'module_not_implemented', requiredModule: 'advanced' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'interpretive_text', groupName: 'Interpretive Text', fieldKey: 'personality_summary', displayLabel: 'Personality Summary', sourceType: 'llm_grounded_text', requiredChartPaths: ['canonical_chart_json_v2.sections.lagna.fields.sign', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Moon.sign'], calculationModule: 'llm', testIds: ['report-field-personality-summary'], unavailablePolicy: { reason: 'unsafe_to_answer' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'interpretive_text', groupName: 'Interpretive Text', fieldKey: 'career_summary', displayLabel: 'Career Summary', sourceType: 'llm_grounded_text', requiredChartPaths: ['canonical_chart_json_v2.sections.lagna.fields.sign', 'canonical_chart_json_v2.sections.vimshottari.fields.current_mahadasha'], calculationModule: 'llm', testIds: ['report-field-career-summary'], unavailablePolicy: { reason: 'unsafe_to_answer' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'interpretive_text', groupName: 'Interpretive Text', fieldKey: 'relationship_summary', displayLabel: 'Relationship Summary', sourceType: 'llm_grounded_text', requiredChartPaths: ['canonical_chart_json_v2.sections.lagna.fields.sign', 'canonical_chart_json_v2.sections.planetaryPositions.fields.Venus.sign'], calculationModule: 'llm', testIds: ['report-field-relationship-summary'], unavailablePolicy: { reason: 'unsafe_to_answer' }, riskLevel: 'HIGH', versionedSettingsRequired: [], enabled: true },
  { groupId: 'interpretive_text', groupName: 'Interpretive Text', fieldKey: 'remedy_guidance', displayLabel: 'Remedy Guidance', sourceType: 'llm_grounded_text', requiredChartPaths: ['canonical_chart_json_v2.sections.advanced.outerPlanets', 'canonical_chart_json_v2.sections.vimshottari.fields.current_mahadasha'], calculationModule: 'llm', testIds: ['report-field-remedy-guidance'], unavailablePolicy: { reason: 'unsafe_to_answer' }, riskLevel: 'BLOCKER', versionedSettingsRequired: [], enabled: true },
  { groupId: 'interpretive_text', groupName: 'Interpretive Text', fieldKey: 'timing_guidance', displayLabel: 'Timing Guidance', sourceType: 'llm_grounded_text', requiredChartPaths: ['canonical_chart_json_v2.sections.vimshottari.fields.timeline', 'canonical_chart_json_v2.sections.panchang.fields.weekday'], calculationModule: 'llm', testIds: ['report-field-timing-guidance'], unavailablePolicy: { reason: 'unsafe_to_answer' }, riskLevel: 'BLOCKER', versionedSettingsRequired: [], enabled: true },
];

export function getAstroReportFieldRegistry(): readonly AstroReportFieldRegistryEntry[] {
  return ASTRO_REPORT_FIELD_REGISTRY;
}

export function findAstroReportField(fieldKey: string): AstroReportFieldRegistryEntry | undefined {
  return ASTRO_REPORT_FIELD_REGISTRY.find((entry) => entry.fieldKey === fieldKey);
}

export function assertUniqueAstroReportFieldKeys(registry = ASTRO_REPORT_FIELD_REGISTRY): void {
  const seen = new Set<string>();
  for (const entry of registry) {
    if (seen.has(entry.fieldKey)) throw new Error(`Duplicate report field key: ${entry.fieldKey}`);
    seen.add(entry.fieldKey);
  }
}
