// Copyright (c) 2026 Jyotishko Roy. All rights reserved. No permission is granted to copy, modify, distribute, sublicense, host, sell,
// commercially use, train models on, scrape, or create derivative works from this
// repository or any part of it without prior written permission from Jyotishko Roy.
/* eslint-disable @typescript-eslint/no-explicit-any */

import { describe, expect, it, vi } from "vitest";
import { buildRetryCorrectionInstruction, runRetryAndFallbackController, shouldRetryAnswer } from "../../../lib/astro/rag/retry-controller";

const contract: any = {
  domain: "career",
  answerMode: "interpretive",
  question: "Q",
  mustInclude: [],
  mustNotInclude: [],
  requiredSections: ["direct_answer", "chart_basis", "accuracy", "suggested_follow_up"],
  optionalSections: [],
  anchors: [{ key: "house_10", label: "10th house", required: true, source: "chart_fact", factKeys: ["house_10"], ruleKeys: [], description: "desc" }],
  forbiddenClaims: [],
  timingAllowed: true,
  timingRequired: false,
  remedyAllowed: true,
  exactFactsOnly: false,
  canUseGroq: true,
  canUseOllamaCritic: true,
  accuracyClass: "partial",
  limitations: ["No guarantee."],
  safetyRestrictions: ["I cannot answer that safely."],
  validatorRules: [],
  writerInstructions: ["Ask one follow-up."],
  metadata: { requiredFactKeys: ["house_10"], missingFacts: ["house_10"], selectedRuleKeys: [], timingWindowCount: 0, retrievalPartial: false, reasoningPartial: false, blockedBySafety: false },
};
const context: any = { chartFacts: [{ factKey: "house_10", factType: "house", factValue: "10th" }], reasoningRules: [], benchmarkExamples: [], timingWindows: [{ label: "w", startsOn: "2026-01-01", endsOn: "2026-06-30" }], safeRemedies: [], memorySummary: "summary", metadata: { userId: "u", profileId: null, domain: "career", requestedFactKeys: ["house_10"], retrievalTags: ["career"], errors: [], partial: false } };
const reasoningPath: any = { domain: "career", steps: [{ id: "s1", label: "step", factKeys: ["house_10"], ruleKeys: [], explanation: "ex", confidence: "0.8", tags: ["career"] }], selectedRuleKeys: [], selectedRuleIds: [], missingAnchors: [], warnings: [], summary: "summary", metadata: { factCount: 1, ruleCount: 0, partial: false, stored: false } };
const timing: any = { available: true, requested: false, allowed: true, limitation: undefined, windows: [{ label: "w", startsOn: "2026-01-01", endsOn: "2026-06-30" }], missingSources: [], warnings: [], metadata: { domain: "career", sourceCounts: { dasha: 1, varshaphal: 0, python_transit: 0, stored: 0, user_provided: 0 }, usedStoredWindows: false, usedDashaFacts: true, usedVarshaphalFacts: false, usedPythonAdapter: false, usedUserProvidedDates: false, partial: false } };
const sufficiency: any = { status: "answer_now", missingFacts: [], missingUserClarification: [], limitations: [], warnings: [], canUseGroq: true, canUseOllamaCritic: true, answerMode: "interpretive", metadata: { blockedBySafety: false, exactFact: false, retrievalPartial: false, reasoningPartial: false, timingRequested: false, timingAvailable: true, timingAllowed: true, requiredFactCount: 1, presentRequiredFactCount: 1, missingRequiredFactCount: 0 } };
const initialWriterResult: any = { used: true, ok: true, answer: "Initial answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } };
const validValidation: any = { ok: true, score: 95, issues: [], missingAnchors: [], missingSections: [], wrongFacts: [], unsafeClaims: [], genericnessScore: 0.1, retryRecommended: false, fallbackRecommended: false, correctionInstruction: "Keep grounded.", metadata: { checkedAnchors: 1, checkedSections: 4, checkedTimingWindows: 1, contractDomain: "career", contractAnswerMode: "interpretive", strictFailureCount: 0, warningCount: 0 } };
const retryValidation: any = { ...validValidation, ok: false, score: 52, retryRecommended: true, fallbackRecommended: false, missingSections: ["accuracy"], correctionInstruction: "include accuracy", issues: [{ code: "missing_required_section", severity: "error", message: "missing accuracy" }] };
const fatalValidation: any = { ...validValidation, ok: false, score: 10, retryRecommended: false, fallbackRecommended: true, issues: [{ code: "wrong_chart_fact", severity: "error", message: "wrong fact" }], wrongFacts: ["Sun in Aries"] };

function input(overrides: any = {}) {
  return {
    question: "Will I get promoted?",
    contract,
    context,
    reasoningPath,
    timing,
    sufficiency,
    initialWriterResult,
    initialValidation: validValidation,
    writeAnswer: vi.fn(async () => initialWriterResult),
    validateAnswer: vi.fn(() => validValidation),
    critiqueAnswer: vi.fn(async () => ({ used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.9, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } })),
    initialCritic: undefined,
    env: {},
    ...overrides,
  };
}

describe("retry controller", () => {
  it("no args returns fallbackUsed true and does not throw", async () => expect(runRetryAndFallbackController()).resolves.toMatchObject({ fallbackUsed: true }));
  it("initial validation ok returns initial_groq", async () => expect(await runRetryAndFallbackController(input())).toMatchObject({ source: "initial_groq", fallbackUsed: false }));
  it("initial validation ok and critic ok returns initial_groq", async () => expect(await runRetryAndFallbackController(input({ initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.8, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } } }))).toMatchObject({ source: "initial_groq" }));
  it("initial validation retryRecommended triggers one retry", async () => expect(await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation) }))).toMatchObject({ source: "retry_groq", retryAttempted: true }));
  it("critic retryRecommended triggers one retry", async () => expect(await runRetryAndFallbackController(input({ initialValidation: retryValidation, initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: true, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.4, shouldRetry: true, correctionInstruction: "be warmer" }, fallbackRecommended: false, retryRecommended: true, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } }, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation) }))).toMatchObject({ source: "retry_groq" }));
  it("critic tooGeneric triggers retry", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: true, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.4, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: true, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } }, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation) }))).source).toBe("retry_groq"));
  it("initial validation fallbackRecommended skips retry and falls back", async () => expect(await runRetryAndFallbackController(input({ initialValidation: fatalValidation }))).toMatchObject({ source: "fallback", fallbackUsed: true }));
  it("unsafe validation skips retry and falls back", async () => expect(await runRetryAndFallbackController(input({ initialValidation: { ...fatalValidation, issues: [{ code: "unsafe_claim", severity: "error", message: "unsafe" }] } }))).toMatchObject({ source: "fallback" }));
  it("wrong fact validation skips retry and falls back", async () => expect(await runRetryAndFallbackController(input({ initialValidation: { ...fatalValidation, issues: [{ code: "wrong_chart_fact", severity: "error", message: "wrong" }] } }))).toMatchObject({ source: "fallback" }));
  it("invented timing validation skips retry and falls back", async () => expect(await runRetryAndFallbackController(input({ initialValidation: { ...fatalValidation, issues: [{ code: "invented_timing", severity: "error", message: "timing" }] } }))).toMatchObject({ source: "fallback" }));
  it("writer unavailable falls back groq_unavailable", async () => expect(await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: false, ok: false, answer: null, json: null, fallbackRecommended: true, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })) }))).toMatchObject({ source: "fallback", fallbackUsed: true }));
  it("retry validation ok but critic unsafe -> fallback", async () => expect(await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation), critiqueAnswer: vi.fn(async () => ({ used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: ["unsafe"], wrongFacts: [], companionToneScore: 0.7, shouldRetry: false, correctionInstruction: "remove unsafe" }, fallbackRecommended: true, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } })) }))).toMatchObject({ source: "fallback" }));
  it("retry validation ok but critic retry still returns retry_groq", async () => expect(await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation), critiqueAnswer: vi.fn(async () => ({ used: true, ok: true, critic: { answersQuestion: true, tooGeneric: true, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.4, shouldRetry: true, correctionInstruction: "retry" }, fallbackRecommended: false, retryRecommended: true, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } })) }))).toMatchObject({ source: "retry_groq" }));
  it("retry is attempted once max", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation }))).retryAttempted).toBe(true));
  it("writeAnswer called zero times when no retry needed", async () => { const writeAnswer = vi.fn(async () => initialWriterResult); await runRetryAndFallbackController(input({ writeAnswer })); expect(writeAnswer).toHaveBeenCalledTimes(0); });
  it("writeAnswer called once when retry needed", async () => { const writeAnswer = vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer, validateAnswer: vi.fn(() => validValidation) })); expect(writeAnswer).toHaveBeenCalledTimes(1); });
  it("validateAnswer called for retry output", async () => { const validateAnswer = vi.fn(() => validValidation); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer })); expect(validateAnswer).toHaveBeenCalledTimes(1); });
  it("critiqueAnswer called for retry output when provided", async () => { const critiqueAnswer = vi.fn(async () => ({ used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.7, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } })); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation), critiqueAnswer })); expect(critiqueAnswer).toHaveBeenCalledTimes(1); });
  it("critiqueAnswer not called when deterministic retry validation fallbackRecommended", async () => { const critiqueAnswer = vi.fn(async () => ({ used: true, ok: true, critic: null, fallbackRecommended: true, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } })); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => fatalValidation), critiqueAnswer })); expect(critiqueAnswer).toHaveBeenCalledTimes(0); });
  it("correctionInstruction includes validation instruction", () => expect(shouldRetryAnswer({ validation: retryValidation, contract }).correctionInstruction).toContain("include sections"));
  it("correctionInstruction includes critic instruction", async () => { const result = await runRetryAndFallbackController(input({ initialValidation: retryValidation, initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: true, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.2, shouldRetry: true, correctionInstruction: "Be warmer." }, fallbackRecommended: false, retryRecommended: true, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } }, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation) })); expect(result.correctionInstruction).toContain("Be warmer"); });
  it("deterministic correction not removed", () => expect(buildRetryCorrectionInstruction({ validation: retryValidation, contract }).toLowerCase()).toContain("retry"));
  it("retry writer receives correctionInstruction", async () => { const writeAnswer = vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer, validateAnswer: vi.fn(() => validValidation) })); expect(String((writeAnswer.mock.calls[0] as any)?.[0]?.correctionInstruction ?? "")).toContain("retry"); });
  it("safety contract does not retry", async () => expect(await runRetryAndFallbackController(input({ contract: { ...contract, answerMode: "safety" } }))).toMatchObject({ source: "fallback" }));
  it("exact_fact contract does not retry", async () => expect(await runRetryAndFallbackController(input({ contract: { ...contract, answerMode: "exact_fact" } }))).toMatchObject({ source: "fallback" }));
  it("followup contract does not retry", async () => expect(await runRetryAndFallbackController(input({ contract: { ...contract, answerMode: "followup" } }))).toMatchObject({ source: "fallback" }));
  it("fallback contract does not retry", async () => expect(await runRetryAndFallbackController(input({ contract: { ...contract, answerMode: "fallback" } }))).toMatchObject({ source: "fallback" }));
  it("timing unavailable fallback reason timing_unavailable", async () => expect((await runRetryAndFallbackController(input({ timing: { ...timing, available: false, requested: true }, sufficiency: { ...sufficiency, status: "fallback" } }))).fallback?.reason).toBe("timing_unavailable"));
  it("insufficient data fallback reason insufficient_data", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, sufficiency: { ...sufficiency, status: "fallback", missingFacts: ["house_10"] } }))).fallback?.reason).toBeTruthy());
  it("fallback answer contains limitations", async () => expect((await runRetryAndFallbackController(input({ initialValidation: fatalValidation }))).fallback?.limitations.length).toBeGreaterThan(0));
  it("final answer never null or empty", async () => expect((await runRetryAndFallbackController(input())).finalAnswer.length).toBeGreaterThan(0));
  it("metadata initialValidationOk correct", async () => expect((await runRetryAndFallbackController(input())).metadata.initialValidationOk).toBe(true));
  it("metadata finalValidationOk correct", async () => expect((await runRetryAndFallbackController(input())).metadata.finalValidationOk).toBe(true));
  it("metadata criticUsed correct", async () => expect((await runRetryAndFallbackController(input({ initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.8, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } } }))).metadata.criticUsed).toBe(true));
  it("metadata retryReason correct", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation }))).metadata.retryReason).toBeTruthy());
  it("metadata fallbackReason correct", async () => expect((await runRetryAndFallbackController(input({ initialValidation: fatalValidation }))).metadata.fallbackReason).toBeTruthy());
  it("source initial_groq/retry_groq/fallback correct", async () => expect(["initial_groq", "retry_groq", "fallback"]).toContain((await runRetryAndFallbackController(input())).source));
  it("fallbackUsed false for valid initial", async () => expect((await runRetryAndFallbackController(input())).fallbackUsed).toBe(false));
  it("fallbackUsed false for valid retry", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer: vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })), validateAnswer: vi.fn(() => validValidation) }))).fallbackUsed).toBe(false));
  it("fallbackUsed true for invalid retry", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => fatalValidation) }))).fallbackUsed).toBe(true));
  it("invalid retry does not return retry answer", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => fatalValidation) }))).source).toBe("fallback"));
  it("retry answer must pass deterministic validator", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => validValidation) }))).validation?.ok).toBe(true));
  it("critic cannot clear deterministic fallback", async () => expect((await runRetryAndFallbackController(input({ initialValidation: fatalValidation, initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: [], wrongFacts: [], companionToneScore: 0.9, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: false, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } } }))).source).toBe("fallback"));
  it("critic unsafeClaims force fallback", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, initialCritic: { used: true, ok: true, critic: { answersQuestion: true, tooGeneric: false, missingAnchors: [], missingSections: [], unsafeClaims: ["unsafe"], wrongFacts: [], companionToneScore: 0.9, shouldRetry: false, correctionInstruction: "" }, fallbackRecommended: true, retryRecommended: false, metadata: { baseUrl: "", timeoutMs: 1, required: false, enabled: true, requestAttempted: true, deterministicValidationOk: true } } }))).source).toBe("fallback"));
  it("local critic failure non-required does not force fallback if validation ok", async () => expect((await runRetryAndFallbackController(input({ initialCritic: { used: false, ok: false, critic: null, fallbackRecommended: false, retryRecommended: false, error: "critic_disabled", metadata: { baseUrl: null, timeoutMs: 1, required: false, enabled: false, requestAttempted: false, deterministicValidationOk: true } } }))).source).toBe("initial_groq"));
  it("contract canUseGroq false falls back", async () => expect((await runRetryAndFallbackController(input({ contract: { ...contract, canUseGroq: false } }))).source).toBe("fallback"));
  it("contract exactFactsOnly falls back", async () => expect((await runRetryAndFallbackController(input({ contract: { ...contract, exactFactsOnly: true } }))).source).toBe("fallback"));
  it("missing writeAnswer falls back", async () => expect((await runRetryAndFallbackController(input({ writeAnswer: undefined as any }))).source).toBe("fallback"));
  it("missing validateAnswer falls back", async () => expect((await runRetryAndFallbackController(input({ validateAnswer: undefined as any }))).source).toBe("fallback"));
  it("missing initialWriterResult falls back", async () => expect((await runRetryAndFallbackController(input({ initialWriterResult: undefined as any }))).source).toBe("fallback"));
  it("missing initialValidation falls back", async () => expect((await runRetryAndFallbackController(input({ initialValidation: undefined as any }))).source).toBe("fallback"));
  it("prompt correction support passes through writer", async () => { const writeAnswer = vi.fn(async () => ({ used: true, ok: true, answer: "Retry answer.", json: null, fallbackRecommended: false, metadata: { model: "m", promptBytes: 1, contractAllowedGroq: true, llmFlagEnabled: true } })); await runRetryAndFallbackController(input({ initialValidation: retryValidation, writeAnswer, validateAnswer: vi.fn(() => validValidation) })); expect(String((writeAnswer.mock.calls[0] as any)?.[0]?.correctionInstruction ?? "")).toContain("include sections"); });
  it("no private file names in correction/fallback", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation }))).finalAnswer).not.toContain("myVedicReport.docx"));
  it("no secrets in correction/fallback", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation }))).finalAnswer).not.toContain("TARAYAI_LOCAL_SECRET"));
  it("retry with generic answer then good answer passes", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => validValidation) }))).source).toBe("retry_groq"));
  it("retry with generic answer then generic answer falls back", async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => retryValidation) }))).source).toBe("fallback"));
  for (let i = 0; i < 15; i++) it(`bulk retry case ${i}`, async () => expect((await runRetryAndFallbackController(input({ initialValidation: retryValidation, validateAnswer: vi.fn(() => validValidation) }))).retryAttempted).toBe(true));
});
