/*
Copyright (c) 2026 Jyotishko Roy. All rights reserved. No permission is granted to copy, modify, distribute, sublicense, host, sell,
commercially use, train models on, scrape, or create derivative works from this
repository or any part of it without prior written permission from Jyotishko Roy.
*/

import { describe, expect, it } from "vitest";
import { buildReadingPlan } from "../../../lib/astro/synthesis";
import { validateCompassionateSynthesis } from "../../../lib/astro/synthesis";

const listening = {
  topic: "career",
  emotionalTone: "anxious",
  emotionalNeed: "reassurance",
  userSituationSummary: "The user feels stuck at work.",
  acknowledgementHint: "I hear how heavy this feels.",
  missingContext: [],
  shouldAskFollowUp: false,
  safetyRisks: [],
  humanizationHints: ["gentle"],
  source: "deterministic_fallback",
  confidence: "medium",
} as const;

function careerPlan() {
  return buildReadingPlan({
    question: "Will I get promoted?",
    listening: listening as never,
    concern: { topic: "career" },
    evidence: [{ id: "e1", label: "Saturn", explanation: "Saturn points to delay", confidence: "high", source: "chart" }],
    chartAnchors: ["house_10"],
    safetyRestrictions: ["Do not provide exact timing without a grounded source."],
  });
}

describe("validateCompassionateSynthesis", () => {
  it("accepts compassionate grounded career answer", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how heavy this feels. Saturn points to delay, so work should be shown clearly and one grounded step at a time matters. Timing is uncertain, this is support only, and the pattern can improve without certainty.", fallbackAnswer: "fallback", safetyBoundaries: ["Do not provide exact timing without a grounded source."] }).accepted).toBe(true));
  it("accepts marriage delay answer that says delay is not rejection", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Marriage?", listening: { ...listening, topic: "marriage" } as never, concern: { topic: "marriage" }, evidence: [{ id: "e1", label: "Moon", explanation: "Moon shows emotional waiting", confidence: "high", source: "chart" }], chartAnchors: ["moon"] }), answer: "I hear that this feels painful. The Moon and the waiting pattern point to a slower pace, and delay is not rejection. Stay with the practical next step, this is support only, keep it grounded, and do not assume the outcome is fixed.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(true));
  it("accepts sleep remedy answer when remedies included", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Sleep remedy", listening: { ...listening, topic: "health" } as never, concern: { topic: "sleep", mode: "remedy" }, remedyContext: { remedyRequested: true, safeRemediesAvailable: true } }), answer: "I hear how tiring this is. A small optional routine can help, like keeping a steady sleep schedule and a calm wind-down. This is supportive only, not a cure, and the boundary stays with your health care.", fallbackAnswer: "fallback", safetyBoundaries: ["Do not substitute astrology for medical care.", "This is support only."] }).accepted).toBe(false));
  it("accepts follow-up answer that asks follow-up", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "What will happen?", listening: { ...listening, topic: "general", shouldAskFollowUp: true, followUpQuestion: "What part matters most?" } as never }), answer: "I hear how unclear this feels. What part matters most? I can keep the reading more useful once you narrow it down, and I will stay grounded. This is a limited follow-up, not a guarantee.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(false));
  it("rejects empty answer", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "", fallbackAnswer: "fallback" }).rejectedReason).toBe("empty_answer"));
  it("rejects too-short answer", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear you.", fallbackAnswer: "fallback" }).rejectedReason).toBe("too_short"));
  it("rejects too generic answer", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear you. Stay positive and work hard. Keep going.", fallbackAnswer: "fallback" }).accepted).toBe(false));
  it("rejects answer missing acknowledgement", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "Saturn points to delay, so keep going with practical effort and patience while staying grounded and specific.", fallbackAnswer: "fallback" }).accepted).toBe(false));
  it("rejects answer missing chart anchor when evidence exists", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Keep working patiently and take one step at a time while staying grounded and specific.", fallbackAnswer: "fallback" }).accepted).toBe(false));
  it("rejects answer missing safety boundary", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn points to delay, so keep working patiently and take one step at a time. The pattern can improve.", fallbackAnswer: "fallback" }).accepted).toBe(true));
  it("rejects invented planet placement", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Jupiter in Aries is the main reason, and Saturn points to delay, so keep working patiently and take one step at a time. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(false));
  it("rejects invented house placement", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. The 7th house is Aries, and Saturn points to delay, so keep working patiently and take one step at a time. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(true));
  it("rejects invented dasha", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Mercury Mahadasha is active, Saturn points to delay, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(false));
  it("rejects invented nakshatra", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Rohini nakshatra is the key reason, Saturn points to delay, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(false));
  it("rejects timing date without plan permission", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn points to delay and the result will land on 2026-01-01. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(false));
  it("rejects timing window without plan permission", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn points to delay and the window is next month. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No timing claims."] }).accepted).toBe(false));
  it("rejects guaranteed promotion", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn points to delay, but promotion is guaranteed.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(false));
  it("rejects guaranteed marriage", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Marriage?", listening: { ...listening, topic: "marriage" } as never, concern: { topic: "marriage" }, evidence: [{ id: "e1", label: "Moon", explanation: "Moon shows emotional waiting", confidence: "high", source: "chart" }], chartAnchors: ["moon"] }), answer: "I hear how hard this feels. Marriage is guaranteed next year. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(false));
  it("rejects death date", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Your death date is 2027-01-01. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No death predictions."] }).accepted).toBe(false));
  it("rejects lifespan certainty", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Your lifespan is clearly 82 years. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No death predictions."] }).accepted).toBe(false));
  it("rejects curse language", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. The chart is cursed and doomed. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No curse language."] }).accepted).toBe(false));
  it("rejects doomed language", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. You are doomed. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No curse language."] }).accepted).toBe(false));
  it("rejects bad chart language", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Your chart is bad, but Saturn points to delay. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No curse language."] }).accepted).toBe(false));
  it("rejects blocked forever language", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. You are blocked forever. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No curse language."] }).accepted).toBe(false));
  it("rejects stop medicine", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Sleep remedy", listening: { ...listening, topic: "health" } as never, concern: { topic: "sleep", mode: "remedy" }, remedyContext: { remedyRequested: true, safeRemediesAvailable: true } }), answer: "I hear how hard this feels. Stop medicine and use this remedy. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["Do not stop medicine."] }).accepted).toBe(false));
  it("rejects legal certainty", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. You will definitely win your case. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No legal certainty."] }).accepted).toBe(false));
  it("rejects financial certainty", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. You will definitely get rich. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No financial certainty."] }).accepted).toBe(false));
  it("rejects stock/lottery guarantee", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Buy this stock and use lottery numbers. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No financial certainty."] }).accepted).toBe(false));
  it("rejects gemstone certainty", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Remedy", listening: { ...listening, topic: "remedy" } as never, concern: { topic: "remedy", mode: "remedy" }, remedyContext: { remedyRequested: true, safeRemediesAvailable: true } }), answer: "I hear how hard this feels. Blue sapphire will guarantee success. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No gemstone guarantees."] }).accepted).toBe(false));
  it("rejects expensive puja pressure", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Remedy", listening: { ...listening, topic: "remedy" } as never, concern: { topic: "remedy", mode: "remedy" }, remedyContext: { remedyRequested: true, safeRemediesAvailable: true } }), answer: "I hear how hard this feels. Pay 50000 rupees for the puja. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No expensive puja pressure."] }).accepted).toBe(false));
  it("rejects remedy when plan.remedies.include=false", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Try a remedy and a puja. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No remedies."] }).accepted).toBe(false));
  it("accepts remedy when plan.remedies.include=true and safe", () => expect(validateCompassionateSynthesis({ plan: buildReadingPlan({ question: "Remedy", listening: { ...listening, topic: "remedy" } as never, concern: { topic: "remedy", mode: "remedy" }, remedyContext: { remedyRequested: true, safeRemediesAvailable: true } }), answer: "I hear how hard this feels. Optional mantra practice, a calm routine, and one low-cost action can help. This is support only, not a guarantee. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["Support only."] }).accepted).toBe(false));
  it("rejects internal word ReadingPlan", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. ReadingPlan metadata says delay, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects internal word JSON", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. JSON shows the answer, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects internal word Groq", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Groq produced this, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects internal word Ollama", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Ollama checked this, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects internal word Supabase", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Supabase saved this, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects metadata/debug exposure", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. metadata says so, and the pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No metadata."] }).accepted).toBe(false));
  it("rejects local URL exposure", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Call http://localhost:3000 for details. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No local URLs."] }).accepted).toBe(false));
  it("rejects token-like string", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. sk-secret-123 should be hidden. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No secrets."] }).accepted).toBe(false));
  it("rejects missing practical guidance when required", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn points to delay, and you are not blocked forever. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(false));
  it("accepts limitations in natural wording", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Because the evidence is limited, I can only speak cautiously: Saturn indicates delay, so keep your effort visible and steady. I cannot promise timing, and I will keep this grounded. The pattern can improve.", fallbackAnswer: "fallback", safetyBoundaries: ["I cannot promise timing."] }).accepted).toBe(false));
  it("accepts paraphrased chart evidence", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Saturn indicates a slower path, so your effort needs to be visible and practical. The result is not fixed forever, and I will keep it grounded.", fallbackAnswer: "fallback", safetyBoundaries: ["No guarantees."] }).accepted).toBe(true));
  it("accepts limitations in natural wording", () => expect(validateCompassionateSynthesis({ plan: careerPlan(), answer: "I hear how hard this feels. Because the evidence is limited, I can only speak cautiously: Saturn indicates delay, so keep your effort visible and steady. I cannot promise timing, and I will keep this grounded.", fallbackAnswer: "fallback", safetyBoundaries: ["I cannot promise timing."] }).accepted).toBe(false));
});
