insert into public.astro_reasoning_rules (
  rule_key,
  domain,
  title,
  description,
  required_fact_types,
  required_tags,
  reasoning_template,
  weight,
  safety_notes,
  enabled,
  metadata
) values
  (
    'career_promotion_delay_core',
    'career',
    'Career promotion delay core',
    'Generic career rule for interpreting promotion timing and recognition patterns.',
    array['house', 'dasha', 'planet_placement'],
    array['career', 'house_10', 'dasha'],
    'Use the 10th house, 10th lord, and current dasha to discuss recognition, responsibility, and gains. Keep the answer grounded and avoid guarantees.',
    220,
    array['Do not promise promotion timing.', 'Do not imply certainty.'],
    true,
    '{}'::jsonb
  ),
  (
    'career_network_gains_core',
    'career',
    'Career network gains core',
    'Generic career rule for gains through networks, seniors, and communication.',
    array['house', 'planet_placement'],
    array['career', 'house_11'],
    'Interpret the 11th house for gains, networks, communication, and support from colleagues or seniors. Keep the reading cautious and practical.',
    210,
    array['Avoid money guarantees.', 'Avoid claiming specific outcomes.'],
    true,
    '{}'::jsonb
  ),
  (
    'sleep_remedy_core',
    'sleep',
    'Sleep remedy core',
    'Generic sleep rule that stays within safe non-medical guidance.',
    array['house', 'planet_placement'],
    array['sleep', 'moon', 'house_12'],
    'Discuss the Moon, the 12th house, rest patterns, and safe non-medical remedies. Do not present medical treatment or diagnosis.',
    200,
    array['Do not diagnose.', 'Do not replace medical care.'],
    true,
    '{}'::jsonb
  ),
  (
    'marriage_core',
    'marriage',
    'Marriage core',
    'Generic relationship rule for the 7th house and Venus themes.',
    array['house', 'planet_placement'],
    array['marriage', 'house_7', 'venus'],
    'Use the 7th house, 7th lord, and Venus to describe relationship patterns, compatibility themes, and practical cautions without certainty.',
    205,
    array['Avoid marriage prediction certainty.', 'Avoid pressure tactics.'],
    true,
    '{}'::jsonb
  ),
  (
    'money_income_core',
    'money',
    'Money and income core',
    'Generic money rule for income, savings, and gains.',
    array['house', 'planet_placement'],
    array['money', 'house_2', 'house_11'],
    'Interpret income, savings, and gains through the 2nd and 11th houses. Do not give financial guarantees or investment advice disguised as certainty.',
    215,
    array['Do not promise income.', 'Do not present financial guarantees.'],
    true,
    '{}'::jsonb
  ),
  (
    'foreign_relocation_core',
    'foreign',
    'Foreign relocation core',
    'Generic foreign travel and relocation rule.',
    array['house', 'planet_placement'],
    array['foreign', 'house_12', 'rahu'],
    'Discuss foreign, remote, or away-from-birthplace themes using the 12th house and Rahu cautiously. Avoid implying guaranteed relocation.',
    190,
    array['Do not guarantee relocation.', 'Keep interpretation symbolic and practical.'],
    true,
    '{}'::jsonb
  ),
  (
    'timing_grounding_required',
    'timing',
    'Timing grounding required',
    'Rule requiring a grounded timing source before any timing statement.',
    array['dasha'],
    array['timing'],
    'Timing claims require grounded sources such as dasha, varshaphal, stored timing data, python_transit, or user-provided evidence. If the source is missing, do not give a date claim.',
    250,
    array['Do not invent timing.', 'Use only grounded sources.'],
    true,
    '{}'::jsonb
  ),
  (
    'safety_no_certainty_core',
    'safety',
    'Safety no certainty core',
    'Rule that blocks harmful certainty and pressure-based claims.',
    array['safety'],
    array['safety'],
    'Forbid death-date claims, diagnosis claims, legal or financial guarantees, expensive puja pressure, and gemstone certainty. Redirect to safe, bounded guidance.',
    300,
    array['Do not claim death timing.', 'Do not claim diagnosis.', 'Do not pressure for paid remedies.'],
    true,
    '{}'::jsonb
  )
on conflict (rule_key) do update set
  domain = excluded.domain,
  title = excluded.title,
  description = excluded.description,
  required_fact_types = excluded.required_fact_types,
  required_tags = excluded.required_tags,
  reasoning_template = excluded.reasoning_template,
  weight = excluded.weight,
  safety_notes = excluded.safety_notes,
  enabled = excluded.enabled,
  metadata = excluded.metadata;
